return {
	Daily = {
		{
			Name = "Kill 5 Scouts",
			Description = "Defeat 5 Scout enemies.",
			TargetDataName = "Kills.Scout",
			TargetAmount = 5,
			Rewards = { Cash = 250 },
			XP = 100,
		},
		{
			Name = "Kill 5 Soldiers",
			Description = "Defeat 5 Soldier enemies.",
			TargetDataName = "Kills.Soldier",
			TargetAmount = 5,
			Rewards = { Cash = 250 },
			XP = 100,
		},
		{
			Name = "Kill 2 Heavys",
			Description = "Defeat 2 Heavy enemies.",
			TargetDataName = "Kills.Heavy",
			TargetAmount = 2,
			Rewards = { Cash = 300 },
			XP = 120,
		},
		{
			Name = "Kill 1 TNT",
			Description = "Defeat 1 TNT enemy.",
			TargetDataName = "Kills.TNT",
			TargetAmount = 1,
			Rewards = { Cash = 300 },
			XP = 120,
		},
		{
			Name = "Kill 1 Boss",
			Description = "Defeat 1 Boss enemy.",
			TargetDataName = "Kills.Boss",
			TargetAmount = 1,
			Rewards = { Cash = 500 },
			XP = 150,
		},
		--[[{
			Name = "Upgrade Tower",
			Description = "Upgrade any tower once.",
			TargetDataName = "TowerUpgrades",
			TargetAmount = 1,
			Rewards = { Cash = 300 },
			XP = 100,
		},
		{
			Name = "Win 1 Round",
			Description = "Win one round.",
			TargetDataName = "Wins",
			TargetAmount = 1,
			Rewards = { Cash = 400 },
			XP = 150,
		},
		{
			Name = "Gain 2k Cash in a Round",
			Description = "Earn 2,000 cash in a single round.",
			TargetDataName = "CashGained",
			TargetAmount = 2000,
			Rewards = { Cash = 200 },
			XP = 80,
		},
		{
			Name = "Gain 500 Cash in a Round",
			Description = "Earn 500 cash in a single round.",
			TargetDataName = "CashGained",
			TargetAmount = 500,
			Rewards = { Cash = 100 },
			XP = 50,
		},--]]
	},

	Weekly = {
		{
			Name = "Kill 15 Scouts",
			Description = "Defeat 15 Scout enemies.",
			TargetDataName = "Kills.Scout",
			TargetAmount = 15,
			Rewards = { Cash = 800 },
			XP = 300,
		},
		{
			Name = "Kill 20 Soldiers",
			Description = "Defeat 20 Soldier enemies.",
			TargetDataName = "Kills.Soldier",
			TargetAmount = 20,
			Rewards = { Cash = 900 },
			XP = 350,
		},
		{
			Name = "Kill 5 Heavys",
			Description = "Defeat 5 Heavy enemies.",
			TargetDataName = "Kills.Heavy",
			TargetAmount = 5,
			Rewards = { Cash = 1000 },
			XP = 400,
		},
		{
			Name = "Kill 10 TNT",
			Description = "Defeat 10 TNT enemies.",
			TargetDataName = "Kills.TNT",
			TargetAmount = 10,
			Rewards = { Cash = 1000 },
			XP = 400,
		},
		{
			Name = "Kill 5 Boss",
			Description = "Defeat 5 Boss enemies.",
			TargetDataName = "Kills.Boss",
			TargetAmount = 5,
			Rewards = { Cash = 1200 },
			XP = 500,
		},
		--[[{
			Name = "Upgrade Tower",
			Description = "Upgrade any tower 5 times.",
			TargetDataName = "TowerUpgrades",
			TargetAmount = 5,
			Rewards = { Cash = 800 },
			XP = 250,
		},
		{
			Name = "Win 5 Rounds",
			Description = "Win 5 rounds.",
			TargetDataName = "Wins",
			TargetAmount = 5,
			Rewards = { Cash = 1500 },
			XP = 600,
		},
		{
			Name = "Gain 10k Cash in a Round",
			Description = "Earn 10,000 cash in a single round.",
			TargetDataName = "CashGained",
			TargetAmount = 10000,
			Rewards = { Cash = 1000 },
			XP = 350,
		},
		{
			Name = "Gain 5k Cash in a Round",
			Description = "Earn 5,000 cash in a single round.",
			TargetDataName = "CashGained",
			TargetAmount = 5000,
			Rewards = { Cash = 600 },
			XP = 250,
		},--]]
	},

	Monthly = {
		{
			Name = "Kill 70 Scouts",
			Description = "Defeat 70 Scout enemies.",
			TargetDataName = "Kills.Scout",
			TargetAmount = 70,
			Rewards = { Cash = 2500 },
			XP = 1000,
		},
		{
			Name = "Kill 65 Soldiers",
			Description = "Defeat 65 Soldier enemies.",
			TargetDataName = "Kills.Soldier",
			TargetAmount = 65,
			Rewards = { Cash = 2500 },
			XP = 1000,
		},
		{
			Name = "Kill 45 Heavys",
			Description = "Defeat 45 Heavy enemies.",
			TargetDataName = "Kills.Heavy",
			TargetAmount = 45,
			Rewards = { Cash = 3000 },
			XP = 1200,
		},
		{
			Name = "Kill 25 TNT",
			Description = "Defeat 25 TNT enemies.",
			TargetDataName = "Kills.TNT",
			TargetAmount = 25,
			Rewards = { Cash = 3000 },
			XP = 1200,
		},
		{
			Name = "Kill 15 Boss",
			Description = "Defeat 15 Boss enemies.",
			TargetDataName = "Kills.Boss",
			TargetAmount = 15,
			Rewards = { Cash = 4000 },
			XP = 1500,
		},
		--[[{
			Name = "Upgrade Tower",
			Description = "Upgrade any tower 20 times.",
			TargetDataName = "TowerUpgrades",
			TargetAmount = 20,
			Rewards = { Cash = 2500 },
			XP = 900,
		},
		{
			Name = "Win 20 Rounds",
			Description = "Win 20 rounds.",
			TargetDataName = "Wins",
			TargetAmount = 20,
			Rewards = { Cash = 5000 },
			XP = 2000,
		},
		{
			Name = "Gain 45k Cash in a Round",
			Description = "Earn 45,000 cash in a single round.",
			TargetDataName = "CashGained",
			TargetAmount = 45000,
			Rewards = { Cash = 3000 },
			XP = 1000,
		},
		{
			Name = "Gain 25k Cash in a Round",
			Description = "Earn 25,000 cash in a single round.",
			TargetDataName = "CashGained",
			TargetAmount = 25000,
			Rewards = { Cash = 2000 },
			XP = 800,
		},--]]
	}
}
